spring:
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
      chain:
        cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths:
        - src/main/resources/templates
        - src/main/resources/static
      poll-interval: 500ms
      quiet-period: 200ms
